name: quantecon_scipy_tutorial_2026
channels:
  - default
dependencies:
  - python=3.13
  - anaconda
  - pip
  - pip:
    - jupyter-book>=1.0.0,<2.0
    - jax
    - matplotlib
    - numpy
    - quantecon-book-theme
    - sphinx-tojupyter
    - sphinxext-rediraffe
    - sphinx-exercise
    - sphinx-proof
    - sphinxcontrib-youtube
    - sphinx-togglebutton
    - sphinx-reredirects
